name: Docker-CI
on: 
  push:
    branches-ignore:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
     image: python:3.8
     volumes:
        - .:/app
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Running testing
      run: |
       python docker-test.py